### ISSUE TITLE
Can't find Board Display name for TE0723-07S

### ISSUE THREAD

**Issue by jpotter0** [duartegalvao/ArduZynq-Tutorials#1]
I am attempting to follow your tutorial on using the ArduZynq boards. I recently purchased a TE0720-03-1CR and TE705-04, but I haven't found any information on how to get started. Then I saw your tutorial and realized I had purchased a TE0723-03-07S-1C about 6 months ago. I then followed your tutorial and made it to the Default Part page in New Project. At first, I saw only 5 parts in the list. Then I clicked 0n Update Board Repositories and downloaded a long list. Unfortunately, the TE0723 boards are not on the list. I clicked on other names which took me to a page describing the particular board. I know that a similar page exists for the TE0723 board because I have seen the page. I have not been successful in trying to change the name of the default board. All I get is the same drop down list with the TE0723 boards missing. Can you give me some guidance on how to fix this?

Thanks, Jim

**Comment by duartegalvao** [comment]
Hi Jim,

Did you correctly follow the step 1.1 of this tutorial? I understand it might not be very explicit (I will consider updating it soon), but you need to load the board files from the TE0723 reference design onto vivado first. That "Update Board Repositories" button won't lead you anywhere.

Here's the reference design download page: https://shop.trenz-electronic.de/en/Download/?path=Trenz_Electronic/Modules_and_Module_Carriers/special/TE0723/Reference_Design/2018.3/test_board

The directory structure should look like this:

<img width="946" alt="Captura de ecrã 2019-10-20, às 06 11 33" src="https://user-images.githubusercontent.com/27357203/67155120-d1633480-f300-11e9-9421-278e9e6174b9.png">

You should load the contents of the `board_files` folder into `C:\Xilinx\Vivado\[VERSION]\data\boards\board_files`, as described in step 1.1.

And here is the CSV i'm talking about in the "Default Part" section:

<img width="1686" alt="Captura de ecrã 2019-10-20, às 06 11 55" src="https://user-images.githubusercontent.com/27357203/67155122-da540600-f300-11e9-8575-bcc56d2ba0db.png">

This tells me that on the "Default Part" screen you should choose "TE0723_07S".

Let me know if this worked out for you!

Best regards,
Duarte Galvão

**Comment by jpotter0** [comment]
Duarte,

Thanks for the reply. I remember doing that step, but maybe I put the files in the wrong place. I'll double check that later. Right now it's 1 AM and I will nap for a few hours.

Thanks,

Jim


On October 19, 2019 11:20:26 PM MDT, "Duarte Galvão" <notifications@github.com> wrote:
>Hi Jim,>
>>
>Did you correctly follow the step 1.1 of this tutorial? I understand it
>might not be very explicit (I will consider updating it soon), but you
>need to load the board files from the TE0723 reference design onto
>vivado first. That "Update Board Repositories" button won't lead you
>anywhere.>
>>
>Here's the reference design download page:
>https://shop.trenz-electronic.de/en/Download/?path=Trenz_Electronic/Modules_and_Module_Carriers/special/TE0723/Reference_Design/2018.3/test_board>
>>
>The directory structure should look like this:>
>>
><img width="946" alt="Captura de ecrã 2019-10-20, às 06 11 33"
>src="https://user-images.githubusercontent.com/27357203/67155120-d1633480-f300-11e9-9421-278e9e6174b9.png">>
>>
>You should load the contents of the `board_files` folder into
>`C:\Xilinx\Vivado\[VERSION]\data\boards\board_files`, as described in
>step 1.1.>
>>
>And here is the CSV i'm talking about in the "Default Part" section:>
>>
><img width="1686" alt="Captura de ecrã 2019-10-20, às 06 11 55"
>src="https://user-images.githubusercontent.com/27357203/67155122-da540600-f300-11e9-8575-bcc56d2ba0db.png">>
>>
>This tells me that on the "Default Part" screen you should choose
>"TE0723_07S".>
>>
>Let me know if this worked out for you!>
>>
>Best regards,>
>Duarte Galvão>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/duartegalvao/ArduZynq-Tutorials/issues/1#issuecomment-544221757

James M Potter, PhD, President
JP Accelerator Works, Inc.
2245 47th Street
Los Alamos, NM 87544-3189
USA

Sent from my Android device with K-9 Mail.

**Comment by jpotter0** [comment]
I did everything per the instructions the first time. I repeated the project construction from scratch. Here is the file structure of the test board directory, which is in a custom download area on drive E.
![File structure](https://user-images.githubusercontent.com/45086768/67157751-dcf93000-f2ed-11e9-9d3d-6963ee936a75.jpg)

I went to the page in your link above, downloaded the reference design, and unzipped it. I found the files and copied them to the specified Vivado directory. The TE0723 link still does not show up in the Default Parts list.

**Comment by duartegalvao** [comment]
If you are sure you did everything right, restarted Vivado, and are looking at the "Boards" list (not the "Parts" that's selected by default), then you can try to contact Trenz support, they may be helpful.

When you resolve the issue I would be very grateful if you post your solution here, so I can improve the tutorial. Good luck!

**Comment by jpotter0** [comment]
Thanks for your help!



On October 20, 2019 4:36:29 AM MDT, "Duarte Galvão" <notifications@github.com> wrote:
>If you are sure you did everything right, restarted Vivado, and are
>looking at the "Boards" list (not the "Parts" that's selected by
>default), then you can try to contact Trenz support, they may be
>helpful.
>
>When you resolve the issue I would be very grateful if you post your
>solution here, so I can improve the tutorial. Good luck!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/duartegalvao/ArduZynq-Tutorials/issues/1#issuecomment-544240310

James M Potter, PhD, President
JP Accelerator Works, Inc.
2245 47th Street
Los Alamos, NM 87544-3189
USA

Sent from my Android device with K-9 Mail.

**Comment by jpotter0** [comment]
Duarte,

I got past that problem. Before, I just created a new project without exiting the program. This time I exited and restarted Vivado. That fixed the issue.

Thanks again for your help.

Jim

**Comment by jpotter0** [comment]
Duarte,

Sorry to bother you, but I am confused again. I got to the point where I should be able to program my device. However, the Bitstream field is blank. A search on wrapper*.bit turns up only some design_1_wrapper.bit turns up several instances of an old file with an April 2019 date code.

It appears that I missed a step about exporting the bitstream to the SDK, but I don't see that step anywhere. I get a message "No bitfile found for the design." Can you tell me where I went wrong?

Thanks,

Jim

**Comment by duartegalvao** [comment]
Hello again Jim. Make sure you followed step 1.4 correctly (it takes a while to run, and the interface is not very obvious on whether it's running. Also, you might have to start over the whole SDK part (or at least delete all the design related files from the sdk first).

Also: It's actually not necessary to program the FPGA just to send a hello world via UART. The ArduZynq boards (or at least the ones I have) come pre-programmed with the reference design, which already has the connections you need. So you can move forward and skip the "Program FPGA" step if you don't need to wire up anything else for your code.

Best regards,
Duarte

**Comment by jpotter0** [comment]
Duarte,

Thanks once again! My goal is to learn how to make these things work, so I will go back over step 1.4 to see what I missed. The next step is to move on to a TE0720-03-1CR. I intend to use it a controller for a DDS rf source and time base generator for rf linear accelerators. The DDS system will be digitally phase locked to the accelerator high Q cavity. In the past I have implemented this with a microcontroller and AD9959 DDS. The time base used an NI 9401 cRIO module, sometimes with other cRIO modules to make a complete accelerator control system. The cRIO uses an FPGA programmed using LabVIEW. I was looking into using a 9605 or its new replacement the 9607 sbRIO. However, the software cost is too high for my project.

Then I found that the TE0720 is almost exactly the same as the 9607. I bought one with an expansion board recently, but I haven't been able to get started with it.

I then found your tutorial and realized that I had a TE0723 that I bought 6 months ago and never used. Your tutorial has been a great help in getting started in spite of my bumbling, and you have been a great help when I get stopped by a mistake.

After this my next step will be to learn how to do something useful with the FPGA.

Best regards,

Jim


On October 21, 2019 3:52:24 AM MDT, "Duarte Galvão" <notifications@github.com> wrote:
>Hello again Jim. Make sure you followed step 1.4 correctly (it takes a
>while to run, and the interface is not very obvious on whether it's
>running. Also, you might have to start over the whole SDK part (or at
>least delete all the design related files from the sdk first).
>
>Also: It's actually not necessary to program the FPGA just to send a
>hello world via UART. The ArduZynq boards (or at least the ones I have)
>come pre-programmed with the reference design, which already has the
>connections you need. So you can move forward and skip the "Program
>FPGA" step if you don't need to wire up anything else for your code.
>
>Best regards,
>Duarte
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/duartegalvao/ArduZynq-Tutorials/issues/1#issuecomment-544439905

James M Potter, PhD, President
JP Accelerator Works, Inc.
2245 47th Street
Los Alamos, NM 87544-3189
USA

Sent from my Android device with K-9 Mail.

**Comment by jpotter0** [comment]
Duarte,

I am doing too many things at once. I finally got back to working through your tutorial. The final snag was that hw_server was not running, and I had to manually run it. I don't know why.

The program loaded and runs, but I don't see the output text on the SDK Terminal. Maybe this is because I am using the wrong com port, but I don't see how to tell. I don't get an error message and when I look at the com ports on SDK they all check "connected".

I am next going ti tackle TE0720-03-CR. I bought "The ZYNQ Book". It references a different board, but maybe I can puzzle through it. Do you know of tutorials more specific to the TE0720-03-1CR?

Thanks again for your help. You got me unstuck several times.

Jim

**Comment by jpotter0** [comment]
I  just discovered that this issue is still open. Thanks for your help, Duarte.
